packages:
  - "apps/**"
  - "packages/**"
  - "deploy-server/**"

catalog:
  # TypeScript 생태계
  typescript: "^5.9.3"
  "@types/node": "^25.0.3"
  ts-node: "^10.9.2"
  tsx: "^4.21.0"

  # Build Tools
  vite: "^7.2.2"
  vite-plugin-dts: "^4.5.4"
  "@vitejs/plugin-react": "^5.1.0"

  # CSS/Styling
  tailwindcss: "^3.4.14"
  autoprefixer: "^10.4.20"
  postcss: "^8.4.49"

  # Linting & Formatting
  eslint: "^9"
  prettier: "^3"
  "@typescript-eslint/eslint-plugin": "^8"
  "@typescript-eslint/parser": "^8.34.0"
  "eslint-config-prettier": "^10.1.5"

  # Git Hooks
  husky: "^9.1.7"
  lint-staged: "^16.2.6"

  # Utilities
  dotenv: "^17.2.3"
  puppeteer: "^24.29.1"

catalogs:
  react:
    react: "^19.2.3"
    react-dom: "^19.2.3"
    "@types/react": "^19.0.4"
    "@types/react-dom": "^19.0.2"
