packages:
  - "apps/**"
  - "packages/**"

catalog:
  "@biomejs/biome": "1.9.4"
  husky: "^9.1.7"
  lint-staged: "^15.4.3"
  typescript: "^5.7.3"
  ts-node: "^10.9.2"
  "@types/node": "^22.13.2"
  autoprefixer: "^10.4.20"
  postcss: "^8.4.49"
  tailwindcss: "^3.4.14"
  vite: "^5.0.0"
  vite-plugin-dts: "^3.2.0"
  "@vitejs/plugin-react": "^4.3.4"
  tsx: "^4.19.3"
  puppeteer: "^24.4.0"
  dotenv: "^16.4.7"

catalogs:
  react18:
    react: "^18.3.1"
    react-dom: "^18.3.1"
    "@types/react": "^18.3.18"
    "@types/react-dom": "^18.3.5"
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": "^19.0.4"
    "@types/react-dom": "^19.0.2"
