name: Deployment devom

permissions:
  actions: read
  contents: read
  pages: write

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "apps/archive/**"
      - "apps/todolist/**"
      - "packages/utils/**"
  workflow_run:
    workflows:
      - "Blog Screenshot Automation"
      - "CI" # CI 성공 후 배포
    types:
      - completed
    branches:
      - master

jobs:
  build:
    if: |
      (github.event.workflow_run.workflow.name == 'CI' && github.event.workflow_run.conclusion == 'success') ||
      github.event_name == 'push' ||
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'pull_request'
    runs-on: ubuntu-22.04
    outputs:
      page_url: ${{ steps.set_output.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build dependencies
        run: |
          pnpm --filter=@devom/utils build
          pnpm --filter=@devom/todolist build

      - name: Build Archive App
        run: pnpm build
        working-directory: apps/archive

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/archive/dist

      - name: Set page_url output
        id: set_output
        run: echo "page_url=${{ github.server_url }}/${{ github.repository }}/deployments" >> $GITHUB_ENV

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ needs.build.outputs.page_url }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/deploy-pages@v4
