name: Workflows Test

on:
  workflow_dispatch:
    inputs:
      stage:
        description: "The stage to deploy to"
        required: true
        type: choice
        options:
          - dev
          - alpha

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
          
      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Deploy to ${{ github.event.inputs.stage }}
        if: github.event.inputs.stage == 'dev' || github.event.inputs.stage == 'alpha'
        run: pnpm --filter @devom/api deploy:${{ github.event.inputs.stage }}

        # working-directory: packages/api
        # run: pnpm run deploy:${{ github.event.inputs.stage }}
